Apothecary - OpenSSL Formula Fixes

diff --git a/scripts/apothecary/apothecary b/scripts/apothecary/apothecary
--- a/scripts/apothecary/apothecary
+++ b/scripts/apothecary/apothecary
@@ -925,15 +925,23 @@ function  dump_output() {
 	fi
 }
 function  error_handler() {
+
+
 	echo ERROR: An error was encountered with the build.
 	dump_output
 	# nicely terminate the ping output loop
 	if [ -z "$PING_LOOP_PID" ]; then
 		echo "Loop PID not set."
 	else 
-		kill $PING_LOOP_PID
+		kill $PING_LOOP_PID || true
 	fi
-	exit 1
+
+	JOB="$0"              # job name
+    LASTLINE="$1"         # line of error occurrence
+    LASTERR="$2"          # error code
+    echo "ERROR in ${JOB} : line ${LASTLINE} with exit code ${LASTERR}"
+
+	exit "${LASTERR}"
 }
 
 ################################################################################
