apothecary: reenable stop on errors

diff --git a/scripts/apothecary/apothecary b/scripts/apothecary/apothecary
--- a/scripts/apothecary/apothecary
+++ b/scripts/apothecary/apothecary
@@ -206,15 +206,15 @@ examples:
 
 #set -x # run script in debug mode
 
-#set -o pipefail  # trace ERR through pipes
-#set -o errtrace  # trace ERR through 'time command' and other functions
-#set -o nounset   # set -u : exit the script if you try to use an uninitialized variable
-#set -o errexit   # set -e : exit the script if any statement returns a non-true return value
+set -o pipefail  # trace ERR through pipes
+set -o errtrace  # trace ERR through 'time command' and other functions
+set -o nounset   # set -u : exit the script if you try to use an uninitialized variable
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 # trap the killer signals so that we can exit with a good message
-#trap "trapSignal SIGHUP" SIGHUP
-#trap "trapSignal SIGINT" SIGINT
-#trap "trapSignal SIGTERM" SIGTERM
+trap "trapSignal SIGHUP" SIGHUP
+trap "trapSignal SIGINT" SIGINT
+trap "trapSignal SIGTERM" SIGTERM
 
 trapSignal() {
 	echo
@@ -223,7 +223,7 @@ trapSignal() {
 }
 
 # trap any script errors and exit
-#trap "trapError" ERR
+trap "trapError" ERR
 
 trapError() {
 	echo
