updated ofStyler with uncrustify check and better usage info; added styleAddon script; added readme

diff --git a/scripts/dev/style/ofStyler b/scripts/dev/style/ofStyler
--- a/scripts/dev/style/ofStyler
+++ b/scripts/dev/style/ofStyler
@@ -7,8 +7,11 @@
 #
 # 2012 Dan Wilcox <danomatika@gmail.com> for openFrameworks
 #
-# adapted form the call_Uncrustify.sh script generated by Universal Indent GUI
+# adapted from the call_Uncrustify.sh script generated by Universal Indent GUI
 #
+
+# exit this script on an error
+#set -e
 
 # the uncrustify style file
 CONFIG_FILE=openFrameworks_style.cfg
@@ -18,15 +21,54 @@ QUIET=-q
 
 ###
 
+function printUsage() {
+	echo
+	echo "Usage:"
+	echo "	ofStyler dirname filesuffix"
+	echo "	ofStyler filename"
+	echo
+	echo "Example:"
+	echo "	ofStyler ../../../libs/openFrameworks cpp"
+	echo "	ofStyler myFile.cpp"
+	echo
+}
+
+function commandExists() {
+	hash "$1" 2>&-
+}
+
+###
+
+# is uncrustify installed?
+if ! commandExists uncrustify ; then
+	echo
+	echo "ERROR: uncrustify source code formatter not found!"
+	echo
+	echo "please install uncrustify: http://uncrustify.sourceforge.net/"
+	echo "  Mac OSX:"
+	echo "    homebrew: brew install uncrustify"
+	echo "    macports: sudo port install uncrustify"
+	echo "  Ubuntu:"
+	echo "    sudo apt-get install uncrustify"
+	echo "  Windows:"
+	echo "    http://sourceforge.net/projects/uncrustify/files/uncrustify/"
+	echo
+	exit 1
+fi
+
 # get the current working dir
 SCRIPT_DIR=$(dirname $0)
 
 # got any options?
 if [ ! -n "$1" ]; then
-	echo "Syntax is: ofStyler dirname filesuffix"
-	echo "Syntax is: ofStyler filename"
-	echo "Example:   ofStyler ../../../libs/openFrameworks cpp"
+	printUsage
 	exit 1
+fi
+
+# simple check for help flags
+if [ "$1" == "-h" -o "$1" == "--help" ]; then
+	printUsage
+	exit 0
 fi
 
 # recurse through a dir
@@ -55,10 +97,9 @@ else
 		echo "Styling one file $1"
 		uncrustify $QUIET "$1" -c $SCRIPT_DIR/$CONFIG_FILE --no-backup
 	else
-		echo "ERROR: directory or file does not exist!"
-		echo "Syntax is: ofStyler dirname filesuffix"
-		echo "Syntax is: ofStyler filename"
-		echo "Example:   ofStyler ../../../libs/openFrameworks cpp"
+		echo
+		echo "ERROR: directory or file $1 does not exist!"
+		printUsage
 		exit 1
 	fi
 fi
